# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

# network script
$network = <<SCRIPT
echo removing IPs from netB* interfaces
ip addr del `ifconfig | grep netB2 -A 1 | grep inet | awk '{print $2}'`/24 dev netB2
ip addr del `ifconfig | grep netB1 -A 1 | grep inet | awk '{print $2}'`/24 dev netB1
SCRIPT

# nvm script
$nvm = <<SCRIPT
echo emulating 8G file as nvm device 
mkdir -p /var/datera/nvmdevs /var/datera/target/nvmdevs
fallocate -l 4G /var/datera/nvmdevs/nvm1
ln -s /var/datera/nvmdevs/nvm1 /var/datera/nvmdevs/Datera_Nvdevice
SCRIPT

# is cluster running
$clusterrunning = <<SCRIPT
for i in {0..40}
do
   if [ "`dcp -l | grep Cluster: | awk '{print $2}'`" == "CL_RUNNING" ];
   then
      echo "cluster state is " `dcp -l | grep Cluster: | awk '{print $2}'`
      exit 0
   fi
   if [ i == 40 ];
   then
      echo "cluster state is " `dcp -l | grep Cluster: | awk '{print $2}'`
      echo "Could not form cluster in 3 minutes"
      exit 1
   fi
   sleep 5
done
SCRIPT

if ENV['DATERA_USERNAME'].nil? or ENV['DATERA_PASSWORD'].nil?
   puts "You must set the environment variables: DATERA_USERNAME and DATERA_PASSWORD"
   exit 1
end

Vagrant.configure("2") do |config|
    config.vm.define "vm1" do |vm1|	  
	  vm1.vm.box = "DaterOS-vagrant"
	  vm1.ssh.username = ENV['DATERA_USERNAME']
	  vm1.ssh.password = ENV['DATERA_PASSWORD']
	  vm1.ssh.pty= true
	  vm1.vm.network :private_network, :ip => '172.16.211.254', :libvirt__forward_mode => "none"
	  vm1.vm.network :private_network, :ip => '172.17.211.254', :libvirt__forward_mode => "none"
	  vm1.vm.network :private_network, :ip => "192.168.100.254", :libvirt__forward_mode => "none"
	  vm1.vm.network :private_network, :ip => "192.168.110.254", :libvirt__forward_mode => "none"
	  vm1.vm.synced_folder ".", "/vagrant_data", disabled: true, owner: "root", group: "root"
	  # provision
          vm1.vm.provision "shell", 
            inline: $nvm
	  vm1.vm.provision "shell", path: "create_init_file.py"
	  # Customize the amount of memory on the VM:
	  vm1.vm.provider :"libvirt" do |domain|
            domain.management_network_mode = "nat"
	    domain.memory = 4096
	    domain.cpus = 4
	    domain.storage :file, :size => '5G', :path => 'datera-single-node-data1.raw', :bus => 'sata', :device => 'sda', :type => 'raw'
	    domain.storage :file, :size => '20G', :path => 'datera-single-node-data2.raw', :bus => 'sata', :device => 'sdb', :type => 'raw'
	    domain.storage :file, :size => '20G', :path => 'datera-single-node-data3.raw', :bus => 'sata', :device => 'sdc', :type => 'raw'
	  end
    end
    config.vm.define "vm2" do |vm2|	  
	  vm2.vm.box = "DaterOS-vagrant"
	  vm2.ssh.username = ENV['DATERA_USERNAME'] 
	  vm2.ssh.password = ENV['DATERA_PASSWORD']
	  vm2.ssh.pty= true
	  vm2.vm.network :private_network, :ip => '172.16.211.253', :libvirt__forward_mode => "none"
	  vm2.vm.network :private_network, :ip => '172.17.211.253', :libvirt__forward_mode => "none"
	  vm2.vm.network :private_network, :ip => "192.168.100.253", :libvirt__forward_mode => "none"
	  vm2.vm.network :private_network, :ip => "192.168.110.253", :libvirt__forward_mode => "none"
	  vm2.vm.synced_folder ".", "/vagrant_data", disabled: true, owner: "root", group: "root"
	  # provision
          vm2.vm.provision "shell", 
            inline: $nvm
	  vm2.vm.provision "shell", 
            inline: $network
          vm2.vm.provision "shell", 
            inline: "echo DateraVM > /var/datera/conf/CLUSTERNAME"
	  # Customize the amount of memory on the VM:
	  vm2.vm.provider :"libvirt" do |domain|
	    domain.memory = 4096
	    domain.cpus = 4
	    domain.storage :file, :size => '5G', :path => 'datera-nvm2.raw', :bus => 'sata', :device => 'sda', :type => 'raw'
	    domain.storage :file, :size => '20G', :path => 'datera-single-node-data1_2.raw', :bus => 'sata', :device => 'sdb', :type => 'raw'
	    domain.storage :file, :size => '20G', :path => 'datera-single-node-data2_2.raw', :bus => 'sata', :device => 'sdc', :type => 'raw'
          end
    end
    config.vm.define "vm3" do |vm3|	  
	  vm3.vm.box = "DaterOS-vagrant"
	  vm3.ssh.username = ENV['DATERA_USERNAME'] 
	  vm3.ssh.password = ENV['DATERA_PASSWORD']
	  vm3.ssh.pty= true
	  vm3.vm.network :private_network, :ip => '172.16.211.252', :libvirt__forward_mode => "none"
	  vm3.vm.network :private_network, :ip => '172.17.211.252', :libvirt__forward_mode => "none"
	  vm3.vm.network :private_network, :ip => "192.168.100.252", :libvirt__forward_mode => "none"
	  vm3.vm.network :private_network, :ip => "192.168.110.252", :libvirt__forward_mode => "none"
	  vm3.vm.synced_folder ".", "/vagrant_data", disabled: true, owner: "root", group: "root"
	  # provision
          vm3.vm.provision "shell", 
            inline: $nvm
	  vm3.vm.provision "shell", 
            inline: $network
          vm3.vm.provision "shell", 
            inline: "echo DateraVM > /var/datera/conf/CLUSTERNAME"
          vm3.vm.provision "shell", 
            inline: $clusterrunning
	  # Customize the amount of memory on the VM:
	  vm3.vm.provider :"libvirt" do |domain|
	    domain.memory = 4096
	    domain.cpus = 4
	    domain.storage :file, :size => '5G', :path => 'datera-nvm3.raw', :bus => 'sata', :device => 'sda', :type => 'raw'
	    domain.storage :file, :size => '20G', :path => 'datera-single-node-data1_3.raw', :bus => 'sata', :device => 'sdb', :type => 'raw'
	    domain.storage :file, :size => '20G', :path => 'datera-single-node-data2_3.raw', :bus => 'sata', :device => 'sdc', :type => 'raw'
          end
    end
end
